version: '3.8'

services:
  eurekaserver:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    container_name: eurekaserver
    restart: always

  gateway:
    build:
      context: ./Gateway
    ports:
      - "8093:8093"
    container_name: gateway
    depends_on:
      - eurekaserver
    restart: always

  gestionevent:
    build:
      context: ./Event/GestionEvent
    ports:
      - "8085:8085"
    container_name: gestionevent
    depends_on:
      - eurekaserver
    restart: always

  gestionabonnement:
    build:
      context: ./GestionAbonnement
    ports:
      - "8084:8084"
    container_name: gestionabonnement
    depends_on:
      - eurekaserver
    restart: always


  gestionproduit:
    build:
      context: ./GestionProduit
    ports:
      - "8086:8086"
    container_name: gestionproduit
    depends_on:
      - eurekaserver
    restart: always
  gestioncours:
    build:
      context: ./Cours
    ports:
      - "8087:8087"
    container_name: gestioncours
    depends_on:
      - eurekaserver
    restart: always
